version: '3'

services:
  cocudb:
    container_name: cocudb
    image: 'mongo:4.2.2'
    volumes:
      - './data/db:/data/db'
    ports:
      - '27017:27017'
    command: 'mongod'

  cocuapi:
    container_name: cocuapi
    image: 'qrivi/cocuapi:latest'
    restart: always
    ports:
      - '8050:8050'
    links:
      - cocudb
    depends_on:
      - cocudb
